### ISSUE TITLE
Magento 2, 3d secure = false, payment success with non 3d card, but got an error and cannot redirect to payment complete page.

### ISSUE THREAD

**Issue by danielpun** [goceevo/magento2-plugin#2]
We are redirecting to payment complete page.
please check updated code.

**Comment by spsinghats** [comment]
We are redirecting to to payment complete page.
please check updated code.

**Comment by spsinghats** [comment]
Please check updated code.

**Comment by danielpun** [comment]
updated and checked again, but getting this error with success URL.

![image](https://user-images.githubusercontent.com/906936/71396501-5813f500-2655-11ea-9be2-11b7e1a363e0.png)
